name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.3"

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project
        run: flutter analyze

      # Agar test folder nahi hai ya tests nahi likhe hain,
      # to neeche wali 2 lines ko comment ya remove kar do.
      # - name: Run tests
      #   run: flutter test
